general:
  kafka-topic: trader-updates

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true   # helps with deserialization

    # This is important so Spring trusts your Transaction class
    consumer:
      properties:
        spring.json.trusted.packages: com.jpmc.midascore.foundation